notifications:
  email: false
language: python
python:
#- '2.7'
#- '3.4'
#- '3.5'
- '3.6'
os:
- linux
#- osx
#matrix:
#  include:
#  - os: osx
#    language: generic
before_install:
- sudo rm -rf /dev/shm
- sudo ln -s /run/shm /dev/shm
install:
- pip install --only-binary=numpy,scipy numpy scipy
- make install
script:
- make develop
- pytest
after_success:
#- sudo apt install python3-pip
- cd ~ && wget https://nixos.org/releases/patchelf/patchelf-0.9/patchelf-0.9.tar.bz2
- tar xvjf patchelf-0.9.tar.bz2
- cd patchelf-0.9
- ./configure
- sudo make install
- sudo pip install auditwheel
- echo $TRAVIS_BUILD_DIR
- cd $TRAVIS_BUILD_DIR
- python setup.py bdist_wheel
- for FILE in dist/*.whl; do auditwheel repair "$FILE"; done;
- ls -hlrt wheelhouse/