notifications:
  email: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
os:
- linux
#- osx
#matrix:
#  include:
#  - os: osx
#    language: generic
before_install:
- sudo rm -rf /dev/shm
- sudo ln -s /run/shm /dev/shm
install:
- pip install --only-binary=numpy,scipy numpy scipy cibuildwheel==0.4.1
- make install
script:
- make develop
- pytest
- cibuildwheel --output-dir wheelhouse
- pwd
- ls wheelhouse
