language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
notifications:
  email: false

before_install:
  # The next couple lines fix a crash with multiprocessing on Travis
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
install:
  # Use precompiled versions of numpy and scipy to reduce build times
  - pip install --only-binary=numpy,scipy numpy scipy
  - make install
# command to run tests
script:
  - make develop
  - pytest
