"""
A listing of hydrogen atom topologies in molecules.
"""
import mollib as ml

# Amino-acid hydrogen topologies
aminoacids = {'GLY': {'HN': {'target_name': 'N',
                             'other_atom_names': ['CA', 'C-1'],
                             'bond_length': ml.settings.bond_length['N-H'],
                             'function': 'add_one_sp2_h'},
                      'HA': {'target_name': 'CA',
                             'other_atom_names': ['N', 'C'],
                             'bond_length': ml.settings.bond_length['CA-HA'],
                             'function': 'add_two_sp3_h'},
                      },
              'ALA': {'HN': {'target_name': 'N',
                             'other_atom_names': ['CA', 'C-1'],
                             'bond_length': ml.settings.bond_length['N-H'],
                             'function': 'add_one_sp2_h'},
                      'HA': {'target_name': 'CA',
                             'other_atom_names': ['N', 'CB', 'C'],
                             'bond_length': ml.settings.bond_length['CA-HA'],
                             'function': 'add_one_sp3_h'},
                      'HB': {'target_name': 'CB',
                             'other_atom_names': ['CA', 'N'],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_three_sp3_h'},
                      },
              'PRO': {'HA': {'target_name': 'CA',
                             'other_atom_names': ['N', 'CB', 'C'],
                             'bond_length': ml.settings.bond_length['CA-HA'],
                             'function': 'add_one_sp3_h'},
                      'HB': {'target_name': 'CB',
                             'other_atom_names': ['CA', 'CG',],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_two_sp3_h'},
                      'HG': {'target_name': 'CG',
                             'other_atom_names': ['CB', 'CD',],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_two_sp3_h'},
                      'HD': {'target_name': 'CD',
                             'other_atom_names': ['CG', 'N',],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_two_sp3_h'},
                      },
              'ARG': {'HN': {'target_name': 'N',
                             'other_atom_names': ['CA', 'C-1'],
                             'bond_length': ml.settings.bond_length['N-H'],
                             'function': 'add_one_sp2_h'},
                      'HA': {'target_name': 'CA',
                             'other_atom_names': ['N', 'CB', 'C'],
                             'bond_length': ml.settings.bond_length['CA-HA'],
                             'function': 'add_one_sp3_h'},
                      'HB': {'target_name': 'CB',
                             'other_atom_names': ['CA', 'CG', ],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_two_sp3_h'},
                      'HG': {'target_name': 'CG',
                             'other_atom_names': ['CB', 'CD', ],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_two_sp3_h'},
                      'HD': {'target_name': 'CD',
                             'other_atom_names': ['CG', 'NE', ],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_two_sp3_h'},
                      'HE': {'target_name': 'NE',
                             'other_atom_names': ['CZ', 'CD'],
                             'bond_length': ml.settings.bond_length['N-H'],
                             'function': 'add_one_sp2_h'},
                      # FIXME: The ARG guanidino group should be slightly
                      # pyramidal.
                      'HH1': {'target_name': 'NH1',
                             'other_atom_names': ['CZ', 'NH2', ],
                             'bond_length': ml.settings.bond_length['N-H2'],
                             'function': 'add_two_sp2_h'},
                      'HH2': {'target_name': 'NH2',
                             'other_atom_names': ['CZ', 'NH1', ],
                             'bond_length': ml.settings.bond_length['N-H2'],
                             'function': 'add_two_sp2_h'},
                      },
              'ASN': {'HN': {'target_name': 'N',
                             'other_atom_names': ['CA', 'C-1'],
                             'bond_length': ml.settings.bond_length['N-H'],
                             'function': 'add_one_sp2_h'},
                      'HA': {'target_name': 'CA',
                             'other_atom_names': ['N', 'CB', 'C'],
                             'bond_length': ml.settings.bond_length['CA-HA'],
                             'function': 'add_one_sp3_h'},
                      'HB': {'target_name': 'CB',
                             'other_atom_names': ['CA', 'CG', ],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_two_sp3_h'},
                      'HD2': {'target_name': 'ND2',
                             'other_atom_names': ['CG', 'OD1', ],
                             'bond_length': ml.settings.bond_length['N-H2'],
                             'function': 'add_two_sp2_h'},
                      },
              'ASP': {'HN': {'target_name': 'N',
                             'other_atom_names': ['CA', 'C-1'],
                             'bond_length': ml.settings.bond_length['N-H'],
                             'function': 'add_one_sp2_h'},
                      'HA': {'target_name': 'CA',
                             'other_atom_names': ['N', 'CB', 'C'],
                             'bond_length': ml.settings.bond_length['CA-HA'],
                             'function': 'add_one_sp3_h'},
                      'HB': {'target_name': 'CB',
                             'other_atom_names': ['CA', 'CG', ],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_two_sp3_h'},
                      # FIXME: Add protonation state of OD.
                      },
              'CYS': {'HN': {'target_name': 'N',
                             'other_atom_names': ['CA', 'C-1'],
                             'bond_length': ml.settings.bond_length['N-H'],
                             'function': 'add_one_sp2_h'},
                      'HA': {'target_name': 'CA',
                             'other_atom_names': ['N', 'CB', 'C'],
                             'bond_length': ml.settings.bond_length['CA-HA'],
                             'function': 'add_one_sp3_h'},
                      'HB': {'target_name': 'CB',
                             'other_atom_names': ['CA', 'SG', ],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_two_sp3_h'},
                      # FIXME: Add reduced/oxidized SH.
                      },
              'GLN': {'HN': {'target_name': 'N',
                             'other_atom_names': ['CA', 'C-1'],
                             'bond_length': ml.settings.bond_length['N-H'],
                             'function': 'add_one_sp2_h'},
                      'HA': {'target_name': 'CA',
                             'other_atom_names': ['N', 'CB', 'C'],
                             'bond_length': ml.settings.bond_length['CA-HA'],
                             'function': 'add_one_sp3_h'},
                      'HB': {'target_name': 'CB',
                             'other_atom_names': ['CA', 'CG', ],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_two_sp3_h'},
                      'HG': {'target_name': 'CG',
                             'other_atom_names': ['CB', 'CD', ],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_two_sp3_h'},
                      'HE2': {'target_name': 'NE2',
                             'other_atom_names': ['CD', 'OE1', ],
                             'bond_length': ml.settings.bond_length['N-H2'],
                             'function': 'add_two_sp2_h'},
                      },
              'GLU': {'HN': {'target_name': 'N',
                             'other_atom_names': ['CA', 'C-1'],
                             'bond_length': ml.settings.bond_length['N-H'],
                             'function': 'add_one_sp2_h'},
                      'HA': {'target_name': 'CA',
                             'other_atom_names': ['N', 'CB', 'C'],
                             'bond_length': ml.settings.bond_length['CA-HA'],
                             'function': 'add_one_sp3_h'},
                      'HB': {'target_name': 'CB',
                             'other_atom_names': ['CA', 'CG', ],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_two_sp3_h'},
                      'HG': {'target_name': 'CG',
                             'other_atom_names': ['CB', 'CD', ],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_two_sp3_h'},
                      # FIXME: Add protonation state of OE2.
                      },
              'HIS': {'HN': {'target_name': 'N',
                             'other_atom_names': ['CA', 'C-1'],
                             'bond_length': ml.settings.bond_length['N-H'],
                             'function': 'add_one_sp2_h'},
                      'HA': {'target_name': 'CA',
                             'other_atom_names': ['N', 'CB', 'C'],
                             'bond_length': ml.settings.bond_length['CA-HA'],
                             'function': 'add_one_sp3_h'},
                      'HB': {'target_name': 'CB',
                             'other_atom_names': ['CA', 'CG', ],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_two_sp3_h'},
                      'HD2': {'target_name': 'CD2',
                              'other_atom_names': ['CG', 'NE2'],
                              'bond_length': ml.settings.bond_length['C-H'],
                              'function': 'add_one_sp2_h'},
                      'HE1': {'target_name': 'CE1',
                              'other_atom_names': ['ND1', 'NE2'],
                              'bond_length': ml.settings.bond_length['C-H'],
                              'function': 'add_one_sp2_h'},
                      # FIXME: Add protonation state of HD1/HE2
                      },
              'ILE': {'HN': {'target_name': 'N',
                             'other_atom_names': ['CA', 'C-1'],
                             'bond_length': ml.settings.bond_length['N-H'],
                             'function': 'add_one_sp2_h'},
                      'HA': {'target_name': 'CA',
                             'other_atom_names': ['N', 'CB', 'C'],
                             'bond_length': ml.settings.bond_length['CA-HA'],
                             'function': 'add_one_sp3_h'},
                      'HB': {'target_name': 'CB',
                             'other_atom_names': ['CG1', 'CA', 'CG2'],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_one_sp3_h'},
                      'HG1': {'target_name': 'CG1',
                             'other_atom_names': ['CB', 'CD1'],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_two_sp3_h'},
                      'HG2': {'target_name': 'CG2',
                              'other_atom_names': ['CB', 'CA'],
                              'bond_length': ml.settings.bond_length['C-H'],
                              'function': 'add_three_sp3_h'},
                      'HD1': {'target_name': 'CD1',
                              'other_atom_names': ['CG1', 'CB'],
                              'bond_length': ml.settings.bond_length['C-H'],
                              'function': 'add_three_sp3_h'},
                      },
              'LEU': {'HN': {'target_name': 'N',
                             'other_atom_names': ['CA', 'C-1'],
                             'bond_length': ml.settings.bond_length['N-H'],
                             'function': 'add_one_sp2_h'},
                      'HA': {'target_name': 'CA',
                             'other_atom_names': ['N', 'CB', 'C'],
                             'bond_length': ml.settings.bond_length['CA-HA'],
                             'function': 'add_one_sp3_h'},
                      'HB': {'target_name': 'CB',
                             'other_atom_names': ['CA', 'CG'],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_two_sp3_h'},
                      'HG': {'target_name': 'CG',
                             'other_atom_names': ['CB', 'CD1', 'CD2'],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_one_sp3_h'},
                      'HD1': {'target_name': 'CD1',
                              'other_atom_names': ['CG', 'CD2'],
                              'bond_length': ml.settings.bond_length['C-H'],
                              'function': 'add_three_sp3_h'},
                      'HD2': {'target_name': 'CD2',
                              'other_atom_names': ['CG', 'CD1'],
                              'bond_length': ml.settings.bond_length['C-H'],
                              'function': 'add_three_sp3_h'},
                       },
              'LYS': {'HN': {'target_name': 'N',
                             'other_atom_names': ['CA', 'C-1'],
                             'bond_length': ml.settings.bond_length['N-H'],
                             'function': 'add_one_sp2_h'},
                      'HA': {'target_name': 'CA',
                             'other_atom_names': ['N', 'CB', 'C'],
                             'bond_length': ml.settings.bond_length['CA-HA'],
                             'function': 'add_one_sp3_h'},
                      'HB': {'target_name': 'CB',
                             'other_atom_names': ['CA', 'CG'],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_two_sp3_h'},
                      'HG': {'target_name': 'CG',
                             'other_atom_names': ['CB', 'CD'],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_two_sp3_h'},
                      'HD': {'target_name': 'CD',
                             'other_atom_names': ['CG', 'CE'],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_two_sp3_h'},
                      'HE': {'target_name': 'CE',
                             'other_atom_names': ['CD', 'NZ'],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_two_sp3_h'},
                      'HZ': {'target_name': 'NZ',
                             'other_atom_names': ['CE', 'CD'],
                             'bond_length': ml.settings.bond_length['N-H'],
                             'function': 'add_three_sp3_h'},
                      # FIXME: Add protonation state of HZ
                      },
              'MET': {'HN': {'target_name': 'N',
                             'other_atom_names': ['CA', 'C-1'],
                             'bond_length': ml.settings.bond_length['N-H'],
                             'function': 'add_one_sp2_h'},
                      'HA': {'target_name': 'CA',
                             'other_atom_names': ['N', 'CB', 'C'],
                             'bond_length': ml.settings.bond_length['CA-HA'],
                             'function': 'add_one_sp3_h'},
                      'HB': {'target_name': 'CB',
                             'other_atom_names': ['CA', 'CG'],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_two_sp3_h'},
                      'HG': {'target_name': 'CG',
                             'other_atom_names': ['CB', 'SD'],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_two_sp3_h'},
                      'HE': {'target_name': 'CE',
                             'other_atom_names': ['SD', 'CG'],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_three_sp3_h'},
                      },
              'PHE': {'HN': {'target_name': 'N',
                             'other_atom_names': ['CA', 'C-1'],
                             'bond_length': ml.settings.bond_length['N-H'],
                             'function': 'add_one_sp2_h'},
                      'HA': {'target_name': 'CA',
                             'other_atom_names': ['N', 'CB', 'C'],
                             'bond_length': ml.settings.bond_length['CA-HA'],
                             'function': 'add_one_sp3_h'},
                      'HB': {'target_name': 'CB',
                             'other_atom_names': ['CA', 'CG'],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_two_sp3_h'},
                      'HD1': {'target_name': 'CD1',
                              'other_atom_names': ['CG', 'CE1'],
                              'bond_length': ml.settings.bond_length['C-H'],
                              'function': 'add_one_sp2_h'},
                      'HD2': {'target_name': 'CD2',
                              'other_atom_names': ['CG', 'CE2'],
                              'bond_length': ml.settings.bond_length['C-H'],
                              'function': 'add_one_sp2_h'},
                      'HE1': {'target_name': 'CE1',
                              'other_atom_names': ['CD1', 'CZ'],
                              'bond_length': ml.settings.bond_length['C-H'],
                              'function': 'add_one_sp2_h'},
                      'HE2': {'target_name': 'CE2',
                              'other_atom_names': ['CD2', 'CZ'],
                              'bond_length': ml.settings.bond_length['C-H'],
                              'function': 'add_one_sp2_h'},
                      'HZ': {'target_name': 'CZ',
                              'other_atom_names': ['CE1', 'CE2'],
                              'bond_length': ml.settings.bond_length['C-H'],
                              'function': 'add_one_sp2_h'},
                      },
              'SER': {'HN': {'target_name': 'N',
                             'other_atom_names': ['CA', 'C-1'],
                             'bond_length': ml.settings.bond_length['N-H'],
                             'function': 'add_one_sp2_h'},
                      'HA': {'target_name': 'CA',
                             'other_atom_names': ['N', 'CB', 'C'],
                             'bond_length': ml.settings.bond_length['CA-HA'],
                             'function': 'add_one_sp3_h'},
                      'HB': {'target_name': 'CB',
                             'other_atom_names': ['CA', 'OG'],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_two_sp3_h'},
                      # FIXME: Add protonation state of HG
                      },
              'THR': {'HN': {'target_name': 'N',
                             'other_atom_names': ['CA', 'C-1'],
                             'bond_length': ml.settings.bond_length['N-H'],
                             'function': 'add_one_sp2_h'},
                      'HA': {'target_name': 'CA',
                             'other_atom_names': ['N', 'CB', 'C'],
                             'bond_length': ml.settings.bond_length['CA-HA'],
                             'function': 'add_one_sp3_h'},
                      'HB': {'target_name': 'CB',
                             'other_atom_names': ['CA', 'CG2', 'OG1'],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_one_sp3_h'},
                      'HG2': {'target_name': 'CG2',
                              'other_atom_names': ['CB', 'OG1'],
                              'bond_length': ml.settings.bond_length['C-H'],
                              'function': 'add_three_sp3_h'},
                      # FIXME: Add protonation state of HG1
                      },
              'TRP': {'HN': {'target_name': 'N',
                             'other_atom_names': ['CA', 'C-1'],
                             'bond_length': ml.settings.bond_length['N-H'],
                             'function': 'add_one_sp2_h'},
                      'HA': {'target_name': 'CA',
                             'other_atom_names': ['N', 'CB', 'C'],
                             'bond_length': ml.settings.bond_length['CA-HA'],
                             'function': 'add_one_sp3_h'},
                      'HB': {'target_name': 'CB',
                             'other_atom_names': ['CA', 'CG'],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_two_sp3_h'},
                      'HD1': {'target_name': 'CD1',
                              'other_atom_names': ['CG', 'NE1'],
                              'bond_length': ml.settings.bond_length['C-H'],
                              'function': 'add_one_sp2_h'},
                      'HE1': {'target_name': 'NE1',
                              'other_atom_names': ['CD1', 'CE2'],
                              'bond_length': ml.settings.bond_length['N-H'],
                              'function': 'add_one_sp2_h'},
                      'HZ2': {'target_name': 'CZ2',
                              'other_atom_names': ['CE2', 'CH2'],
                              'bond_length': ml.settings.bond_length['C-H'],
                              'function': 'add_one_sp2_h'},
                      'HH2': {'target_name': 'CH2',
                              'other_atom_names': ['CZ2', 'CZ3'],
                              'bond_length': ml.settings.bond_length['C-H'],
                              'function': 'add_one_sp2_h'},
                      'HZ3': {'target_name': 'CZ3',
                              'other_atom_names': ['CE3', 'CH2'],
                              'bond_length': ml.settings.bond_length['C-H'],
                              'function': 'add_one_sp2_h'},
                      'HE3': {'target_name': 'CE3',
                              'other_atom_names': ['CD2', 'CZ3'],
                              'bond_length': ml.settings.bond_length['C-H'],
                              'function': 'add_one_sp2_h'},
                      },
              'TYR': {'HN': {'target_name': 'N',
                             'other_atom_names': ['CA', 'C-1'],
                             'bond_length': ml.settings.bond_length['N-H'],
                             'function': 'add_one_sp2_h'},
                      'HA': {'target_name': 'CA',
                             'other_atom_names': ['N', 'CB', 'C'],
                             'bond_length': ml.settings.bond_length['CA-HA'],
                             'function': 'add_one_sp3_h'},
                      'HB': {'target_name': 'CB',
                             'other_atom_names': ['CA', 'CG'],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_two_sp3_h'},
                      'HD1': {'target_name': 'CD1',
                              'other_atom_names': ['CG', 'CE1'],
                              'bond_length': ml.settings.bond_length['C-H'],
                              'function': 'add_one_sp2_h'},
                      'HD2': {'target_name': 'CD2',
                              'other_atom_names': ['CG', 'CE2'],
                              'bond_length': ml.settings.bond_length['C-H'],
                              'function': 'add_one_sp2_h'},
                      'HE1': {'target_name': 'CE1',
                              'other_atom_names': ['CD1', 'CZ'],
                              'bond_length': ml.settings.bond_length['C-H'],
                              'function': 'add_one_sp2_h'},
                      'HE2': {'target_name': 'CE2',
                              'other_atom_names': ['CD2', 'CZ'],
                              'bond_length': ml.settings.bond_length['C-H'],
                              'function': 'add_one_sp2_h'},
                      # FIXME: add HH proton correctly.
                      },
              'VAL': {'HN': {'target_name': 'N',
                             'other_atom_names': ['CA', 'C-1'],
                             'bond_length': ml.settings.bond_length['N-H'],
                             'function': 'add_one_sp2_h'},
                      'HA': {'target_name': 'CA',
                             'other_atom_names': ['N', 'CB', 'C'],
                             'bond_length': ml.settings.bond_length['CA-HA'],
                             'function': 'add_one_sp3_h'},
                      'HB': {'target_name': 'CB',
                             'other_atom_names': ['CA', 'CG1', 'CG2'],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_one_sp3_h'},
                      'HG1': {'target_name': 'CG1',
                             'other_atom_names': ['CB', 'CG2'],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_three_sp3_h'},
                      'HG2': {'target_name': 'CG2',
                             'other_atom_names': ['CB', 'CG1'],
                             'bond_length': ml.settings.bond_length['C-H'],
                             'function': 'add_three_sp3_h'},
                      },
              }

# Replace 'HN' atom name if settings has a different value
if ml.settings.amide_atom_name != 'HN':
    for res, h_dict in aminoacids.items():
        if 'HN' in h_dict:
            h_dict[ml.settings.amide_atom_name] = h_dict['HN']
